[project]
name = "medicalimage-pgtd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "diffusers>=0.34.0",
    "jupyter>=1.1.1",
    "monai[all]>=1.5.0",
    "transformers>=4.53.2",
]
